name: Trigger Tests in Tester Repo

on:
  push:
    branches:
      - main   # You can specify which branch you want this to be triggered on
      - dev    # This is another common branch for development changes

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Developer Repo
      uses: actions/checkout@v2
      
    - name: Set up Git to interact with the Tester Repository
      run: |
        git config --global user.name "Sneha6396"
        git config --global user.email "ikuttisneha@gmail.com"
      
    - name: Clone Tester Repo
      run: |
        git clone https://github.com/Sneha6396/Testing.git
        cd Testing
        git checkout main  # Or the relevant branch in the tester repository
        git pull origin main
    
    - name: Merge Developer Changes into Tester Repo
      run: |
        cd Testing
        git merge ${{ github.sha }}  # Merge the latest developer changes into tester repo

    - name: Install Dependencies in Tester Repo
      run: |
        cd Testing
        npm install  # Or the relevant command to install dependencies in the tester repo

    - name: Run Tests in Tester Repo
      run: |
        cd Testing
        npm test  # Run your test suite in the tester repository
